package jyt.geconomicus.helper;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.TableGenerator;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlTransient;

/**
 * A player in the game.
 * @author jytou
 */
@Entity
public class Player implements Serializable
{
	// The ID is automatically generated by EclipseLink.
	@TableGenerator(
		name="playerGen",
		table="ID_GEN",
		pkColumnName="GEN_KEY",
		valueColumnName="GEN_VALUE",
		pkColumnValue="PLAYER_ID",
		allocationSize=1
	)
	@XmlTransient
	@GeneratedValue(strategy=GenerationType.TABLE, generator="playerGen")
	@Id
	private Integer id;

	// The game in which this player is playing
	@XmlIDREF
	@ManyToOne
	@JoinColumn(nullable=false)
	private Game game;

	// The name of the player
	@XmlID
	private String name;

	// True if the player is active in the game (has joined and did not quit), false otherwise.
	private boolean active;
	// The current debt of the player towards the bank
	private int curDebt;
	// The current interest owed by the player towards the bank. Note that we could easily
	// remove the debt field since we already would know from the interest how much he owes.
	// Nice optimization idea.
	private int curInterest;
	// True if the player has visited the bank during the current turn/round or not.
	private boolean visitedBank;

	// Used by EclipseLink to instantiate empty objects.
	@SuppressWarnings("unused")
	private Player()
	{
		super();
	}

	/**
	 * Create a new player in this game
	 * @param pGame
	 * @param pName
	 */
	public Player(Game pGame, String pName)
	{
		super();
		game = pGame;
		game.addPlayer(this);
		name = pName;
		active = false;
		curDebt = 0;
		curInterest = 0;
		visitedBank = true;
	}

	public boolean isActive()
	{
		return active;
	}

	public void setActive(boolean pActive)
	{
		active = pActive;
	}

	public int getCurDebt()
	{
		return curDebt;
	}

	public void setCurDebt(int pCurDebt)
	{
		curDebt = pCurDebt;
	}

	public int getCurInterest()
	{
		return curInterest;
	}

	public void setCurInterest(int pCurInterest)
	{
		curInterest = pCurInterest;
	}

	@XmlTransient
	public String getName()
	{
		return name;
	}

	public Integer getId()
	{
		return id;
	}

	public boolean hasVisitedBank()
	{
		return visitedBank;
	}

	public boolean isVisitedBank()
	{
		return visitedBank;
	}

	public void setVisitedBank(boolean pVisitedBank)
	{
		visitedBank = pVisitedBank;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		// To be used only in the CLI version
		return "#" + getId() + " - " + getName() + (isActive() ? (getCurDebt() > 0 ? " - debt " + getCurDebt() + " - interest " + getCurInterest() : "") : " INACTIVE"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$
	}

	public void setName(String pName)
	{
		name = pName;
	}
}
